#[allow(dead_code)]
fn format(hex: u8) -> String {
    format!("{:01$x}", hex, 2)
}
#[allow(dead_code)]
pub fn disassemble(buffer: Vec<u8>) {
    let mut pc: usize = 0;
    while pc < buffer.len() {
        match buffer[pc] {
            0x00 => { println!("NOP"); pc += 1; },
            0x01 => { println!("LXI     B,${}{}", format(buffer[pc+2]), format(buffer[pc+1])); pc += 3; },
            0x02 => { println!("STAX    B"); pc += 1; },
            0x03 => { println!("INX     B"); pc += 1; },
            0x04 => { println!("INR     B"); pc += 1; },
            0x05 => { println!("DCR     B"); pc += 1; },
            0x06 => { println!("MVI     B,${}", format(buffer[pc+1])); pc = pc + 2},
            0x07 => { println!("RLC"); pc += 1; },
            0x08 => { println!("NOP"); pc += 1; },
            0x09 => { println!("DAD     B"); pc += 1; },
            0x0a => { println!("LDAX    B"); pc += 1; },
            0x0b => { println!("DCX     B"); pc += 1; },
            0x0c => { println!("INR     C"); pc += 1; },
            0x0d => { println!("DCR     C"); pc += 1; },
            0x0e => { println!("MVI     C,${}", format(buffer[pc+1])); pc += 2; },
            0x0f => { println!("RRC"); pc += 1; },
            0x10 => { println!("NOP"); pc += 1; },
            0x11 => { println!("LXI     D,${}{}", format(buffer[pc+2]), format(buffer[pc+1])); pc += 3; },
            0x12 => { println!("STAX    D"); pc += 1; },
            0x13 => { println!("INX     D"); pc += 1; },
            0x14 => { println!("INR     D"); pc += 1; },
            0x15 => { println!("DCR     D"); pc += 1; },
            0x16 => { println!("MVI     D,${}", format(buffer[pc+1])); pc += 2; },
            0x17 => { println!("RAL"); pc += 1; },
            0x18 => { println!("NOP"); pc += 1; },
            0x19 => { println!("DAD     D"); pc += 1; },
            0x1a => { println!("LDAX    D"); pc += 1; },
            0x1b => { println!("DCX     D"); pc += 1; },
            0x1c => { println!("INR     E"); pc += 1; },
            0x1d => { println!("DCR     E"); pc += 1; },
            0x1e => { println!("MVI     E,${}", format(buffer[pc+1])); pc += 2; },
            0x1f => { println!("RAR"); pc += 1; },
            0x20 => { println!("RIM"); pc += 1; },
            0x21 => { println!("LXI     H,${}{}", format(buffer[pc+2]), format(buffer[pc+1])); pc += 3; },
            0x22 => { println!("SHLD    ${}{}", format(buffer[pc+2]), format(buffer[pc+1])); pc += 3; },
            0x23 => { println!("INX     H"); pc += 1; },
            0x24 => { println!("INR     H"); pc += 1; },
            0x25 => { println!("DCR     H"); pc += 1; },
            0x26 => { println!("MVI     H,${}", format(buffer[pc+1])); pc += 2; },
            0x27 => { println!("DAA"); pc += 1; },
            0x28 => { println!("NOP"); pc += 1; },
            0x29 => { println!("DAD     H"); pc += 1; },
            0x2a => { println!("LHLD    ${}{}", format(buffer[pc+2]), format(buffer[pc+1])); pc += 3; },
            0x2b => { println!("DCX     H"); pc += 1; },
            0x2c => { println!("INR     L"); pc += 1; },
            0x2d => { println!("DCR     L"); pc += 1; },
            0x2e => { println!("MVI     L,${}", format(buffer[pc+1])); pc += 2; },
            0x2f => { println!("CMA"); pc += 1; },
            0x30 => { println!("SIM"); pc += 1; },
            0x31 => { println!("LXI     SP,${}{}", format(buffer[pc+2]), format(buffer[pc+1])); pc += 3; },
            0x32 => { println!("STA     ${}{}", format(buffer[pc+2]), format(buffer[pc+1])); pc += 3; },
            0x33 => { println!("INX     SP"); pc += 1; },
            0x34 => { println!("INR     M"); pc += 1; },
            0x35 => { println!("DCR     M"); pc += 1; },
            0x36 => { println!("MVI     M,${}", format(buffer[pc+1])); pc += 2; },
            0x37 => { println!("STC"); pc += 1; },
            0x38 => { println!("NOP"); pc += 1; },
            0x39 => { println!("DAD     SP"); pc += 1; },
            0x3a => { println!("LDA     ${}{}", format(buffer[pc+2]), format(buffer[pc+1])); pc += 3; },
            0x3b => { println!("DCX     SP"); pc += 1; },
            0x3c => { println!("INR     A"); pc += 1; },
            0x3d => { println!("DCR     A"); pc += 1; },
            0x3e => { println!("MVI     A,${}", format(buffer[pc+1])); pc += 2; },
            0x3f => { println!("CMC"); pc += 1; },
            0x40 => { println!("MOV     B,B"); pc += 1; },
            0x41 => { println!("MOV     B,C"); pc += 1; },
            0x42 => { println!("MOV     B,D"); pc += 1; },
            0x43 => { println!("MOV     B,E"); pc += 1; },
            0x44 => { println!("MOV     B,H"); pc += 1; },
            0x45 => { println!("MOV     B,L"); pc += 1; },
            0x46 => { println!("MOV     B,M"); pc += 1; },
            0x47 => { println!("MOV     B,A"); pc += 1; },
            0x48 => { println!("MOV     C,B"); pc += 1; },
            0x49 => { println!("MOV     C,C"); pc += 1; },
            0x4a => { println!("MOV     C,D"); pc += 1; },
            0x4b => { println!("MOV     C,E"); pc += 1; },
            0x4c => { println!("MOV     C,H"); pc += 1; },
            0x4d => { println!("MOV     C,L"); pc += 1; },
            0x4e => { println!("MOV     C,M"); pc += 1; },
            0x4f => { println!("MOV     C,A"); pc += 1; },
            0x50 => { println!("MOV     D,B"); pc += 1; },
            0x51 => { println!("MOV     D,C"); pc += 1; },
            0x52 => { println!("MOV     D,D"); pc += 1; },
            0x53 => { println!("MOV     D,E"); pc += 1; },
            0x54 => { println!("MOV     D,H"); pc += 1; },
            0x55 => { println!("MOV     D,L"); pc += 1; },
            0x56 => { println!("MOV     D,M"); pc += 1; },
            0x57 => { println!("MOV     D,A"); pc += 1; },
            0x58 => { println!("MOV     E,B"); pc += 1; },
            0x59 => { println!("MOV     E,C"); pc += 1; },
            0x5a => { println!("MOV     E,D"); pc += 1; },
            0x5b => { println!("MOV     E,E"); pc += 1; },
            0x5c => { println!("MOV     E,H"); pc += 1; },
            0x5d => { println!("MOV     E,L"); pc += 1; },
            0x5e => { println!("MOV     E,M"); pc += 1; },
            0x5f => { println!("MOV     E,A"); pc += 1; },
            0x60 => { println!("MOV     H,B"); pc += 1; },
            0x61 => { println!("MOV     H,C"); pc += 1; },
            0x62 => { println!("MOV     H,D"); pc += 1; },
            0x63 => { println!("MOV     H,E"); pc += 1; },
            0x64 => { println!("MOV     H,H"); pc += 1; },
            0x65 => { println!("MOV     H,L"); pc += 1; },
            0x66 => { println!("MOV     H,M"); pc += 1; },
            0x67 => { println!("MOV     H,A"); pc += 1; },
            0x68 => { println!("MOV     L,B"); pc += 1; },
            0x69 => { println!("MOV     L,C"); pc += 1; },
            0x6a => { println!("MOV     L,D"); pc += 1; },
            0x6b => { println!("MOV     L,E"); pc += 1; },
            0x6c => { println!("MOV     L,H"); pc += 1; },
            0x6d => { println!("MOV     L,L"); pc += 1; },
            0x6e => { println!("MOV     L,M"); pc += 1; },
            0x6f => { println!("MOV     L,A"); pc += 1; },
            0x70 => { println!("MOV     M,B"); pc += 1; },
            0x71 => { println!("MOV     M,C"); pc += 1; },
            0x72 => { println!("MOV     M,D"); pc += 1; },
            0x73 => { println!("MOV     M,E"); pc += 1; },
            0x74 => { println!("MOV     M,H"); pc += 1; },
            0x75 => { println!("MOV     M,L"); pc += 1; },
            0x76 => { println!("HLT"); pc += 1; },
            0x77 => { println!("MOV     M,A"); pc += 1; },
            0x78 => { println!("MOV     A,B"); pc += 1; },
            0x79 => { println!("MOV     A,C"); pc += 1; },
            0x7a => { println!("MOV     A,D"); pc += 1; },
            0x7b => { println!("MOV     A,E"); pc += 1; },
            0x7c => { println!("MOV     A,H"); pc += 1; },
            0x7d => { println!("MOV     A,L"); pc += 1; },
            0x7e => { println!("MOV     A,M"); pc += 1; },
            0x7f => { println!("MOV     A,A"); pc += 1; },
            0x80 => { println!("ADD     B"); pc += 1; },
            0x81 => { println!("ADD     C"); pc += 1; },
            0x82 => { println!("ADD     D"); pc += 1; },
            0x83 => { println!("ADD     E"); pc += 1; },
            0x84 => { println!("ADD     H"); pc += 1; },
            0x85 => { println!("ADD     L"); pc += 1; },
            0x86 => { println!("ADD     M"); pc += 1; },
            0x87 => { println!("ADD     A"); pc += 1; },
            0x88 => { println!("ADC     B"); pc += 1; },
            0x89 => { println!("ADC     C"); pc += 1; },
            0x8a => { println!("ADC     D"); pc += 1; },
            0x8b => { println!("ADC     E"); pc += 1; },
            0x8c => { println!("ADC     H"); pc += 1; },
            0x8d => { println!("ADC     L"); pc += 1; },
            0x8e => { println!("ADC     M"); pc += 1; },
            0x8f => { println!("ADC     A"); pc += 1; },
            0x90 => { println!("SUB     B"); pc += 1; },
            0x91 => { println!("SUB     C"); pc += 1; },
            0x92 => { println!("SUB     D"); pc += 1; },
            0x93 => { println!("SUB     E"); pc += 1; },
            0x94 => { println!("SUB     H"); pc += 1; },
            0x95 => { println!("SUB     L"); pc += 1; },
            0x96 => { println!("SUB     M"); pc += 1; },
            0x97 => { println!("SUB     A"); pc += 1; },
            0x98 => { println!("SBB     B"); pc += 1; },
            0x99 => { println!("SBB     C"); pc += 1; },
            0x9a => { println!("SBB     D"); pc += 1; },
            0x9b => { println!("SBB     E"); pc += 1; },
            0x9c => { println!("SBB     H"); pc += 1; },
            0x9d => { println!("SBB     L"); pc += 1; },
            0x9e => { println!("SBB     M"); pc += 1; },
            0x9f => { println!("SBB     A"); pc += 1; },
            0xa0 => { println!("ANA     B"); pc += 1; },
            0xa1 => { println!("ANA     C"); pc += 1; },
            0xa2 => { println!("ANA     D"); pc += 1; },
            0xa3 => { println!("ANA     E"); pc += 1; },
            0xa4 => { println!("ANA     H"); pc += 1; },
            0xa5 => { println!("ANA     L"); pc += 1; },
            0xa6 => { println!("ANA     M"); pc += 1; },
            0xa7 => { println!("ANA     A"); pc += 1; },
            0xa8 => { println!("XRA     B"); pc += 1; },
            0xa9 => { println!("XRA     C"); pc += 1; },
            0xaa => { println!("XRA     D"); pc += 1; },
            0xab => { println!("XRA     E"); pc += 1; },
            0xac => { println!("XRA     H"); pc += 1; },
            0xad => { println!("XRA     L"); pc += 1; },
            0xae => { println!("XRA     M"); pc += 1; },
            0xaf => { println!("XRA     A"); pc += 1; },
            0xb0 => { println!("ORA     B"); pc += 1; },
            0xb1 => { println!("ORA     C"); pc += 1; },
            0xb2 => { println!("ORA     D"); pc += 1; },
            0xb3 => { println!("ORA     E"); pc += 1; },
            0xb4 => { println!("ORA     H"); pc += 1; },
            0xb5 => { println!("ORA     L"); pc += 1; },
            0xb6 => { println!("ORA     M"); pc += 1; },
            0xb7 => { println!("ORA     A"); pc += 1; },
            0xb8 => { println!("CMP     B"); pc += 1; },
            0xb9 => { println!("CMP     C"); pc += 1; },
            0xba => { println!("CMP     D"); pc += 1; },
            0xbb => { println!("CMP     E"); pc += 1; },
            0xbc => { println!("CMP     H"); pc += 1; },
            0xbd => { println!("CMP     L"); pc += 1; },
            0xbe => { println!("CMP     M"); pc += 1; },
            0xbf => { println!("CMP     A"); pc += 1; },
            0xc0 => { println!("RNZ"); pc += 1; },
            0xc1 => { println!("POP     B"); pc += 1; },
            0xc2 => { println!("JNZ     ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xc3 => { println!("JMP     ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xc4 => { println!("CNZ     ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xc5 => { println!("PUSH    B"); pc += 1; },
            0xc6 => { println!("ADI     ${}", format(buffer[pc+1])); pc += 2; },
            0xc7 => { println!("RST     0"); pc += 1; },
            0xc8 => { println!("RZ"); pc += 1; },
            0xc9 => { println!("RET"); pc += 1; },
            0xca => { println!("JZ      ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xcb => { println!("NOP"); pc += 1; },
            0xcc => { println!("CZ      ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xcd => { println!("CALL    ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xce => { println!("ACI     ${}", format(buffer[pc+1])); pc += 2; },
            0xcf => { println!("RST     1"); pc += 1; },
            0xd0 => { println!("RNC"); pc += 1; },
            0xd1 => { println!("POP     D"); pc += 1; },
            0xd2 => { println!("JNC     ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xd3 => { println!("OUT     ${}", format(buffer[pc+1])); pc += 2; },
            0xd4 => { println!("CNC     ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xd5 => { println!("PUSH    D"); pc += 1; },
            0xd6 => { println!("SUI     ${}", format(buffer[pc+1])); pc += 2; },
            0xd7 => { println!("RST     2"); pc += 1; },
            0xd8 => { println!("RC"); pc += 1; },
            0xd9 => { println!("NOP"); pc += 1; },
            0xda => { println!("JC      ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xdb => { println!("IN      ${}", format(buffer[pc+1])); pc += 2; },
            0xdc => { println!("CC      ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xdd => { println!("NOP"); pc += 1; },
            0xde => { println!("SBI     ${}", format(buffer[pc+1])); pc += 2; },
            0xdf => { println!("RST     3"); pc += 1; },
            0xe0 => { println!("RPO"); pc += 1; },
            0xe1 => { println!("POP     H"); pc += 1; },
            0xe2 => { println!("JPO     ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xe3 => { println!("XTHL"); pc += 1; },
            0xe4 => { println!("CPO     ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xe5 => { println!("PUSH    H"); pc += 1; },
            0xe6 => { println!("ANI     ${}", format(buffer[pc+1])); pc += 2; },
            0xe7 => { println!("RST     4"); pc += 1; },
            0xe8 => { println!("RPE"); pc += 1; },
            0xe9 => { println!("PCHL"); pc += 1; },
            0xea => { println!("JPE     ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xeb => { println!("XCHG"); pc += 1; },
            0xec => { println!("CPE     ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xed => { println!("NOP"); pc += 1; },
            0xee => { println!("XRI     ${}", format(buffer[pc+1])); pc += 2; },
            0xef => { println!("RST     5"); pc += 1; },
            0xf0 => { println!("RP"); pc += 1; },
            0xf1 => { println!("POP     PSW"); pc += 1; },
            0xf2 => { println!("JP      ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xf3 => { println!("DI"); pc += 1; },
            0xf4 => { println!("CP      ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xf5 => { println!("PUSH    PSW"); pc += 1; },
            0xf6 => { println!("ORI     ${}", format(buffer[pc+1])); pc += 2; },
            0xf7 => { println!("RST     6"); pc += 1; },
            0xf8 => { println!("RM"); pc += 1; },
            0xf9 => { println!("SPHL"); pc += 1; },
            0xfa => { println!("JM      ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xfb => { println!("EI"); pc += 1; },
            0xfc => { println!("CM      ${}{}",format(buffer[pc+2]),format(buffer[pc+1])); pc += 3; },
            0xfd => { println!("NOP"); pc += 1; },
            0xfe => { println!("CPI     ${}", format(buffer[pc+1])); pc += 2; },
            0xff => { println!("RST     7"); pc += 1; },
            _ => { println!("unknown"); pc += 1; },
        }
    }
}

